export const matchesList = {
  typeMatches: [
    {
      matchType: "League",
      seriesMatches: [
        {
          seriesAdWrapper: {
            seriesId: 4061,
            seriesName: "Indian Premier League 2022",
            matches: [
              {
                matchInfo: {
                  matchId: 46046,
                  seriesId: 4061,
                  seriesName: "Indian Premier League 2022",
                  matchDesc: "33rd Match",
                  matchFormat: "T20",
                  startDate: "1650549600000",
                  endDate: "1650562200000",
                  state: "Complete",
                  status: "Chennai Super Kings won by 3 wkts",
                  team1: {
                    teamId: 62,
                    teamName: "Mumbai Indians",
                    teamSName: "MI",
                    imageId: 225645,
                  },
                  team2: {
                    teamId: 58,
                    teamName: "Chennai Super Kings",
                    teamSName: "CSK",
                    imageId: 225641,
                  },
                  venueInfo: {
                    id: 132,
                    ground: "Dr DY Patil Sports Academy",
                    city: "Mumbai",
                    timezone: "+05:30",
                  },
                  currBatTeamId: 58,
                  seriesStartDt: "1648252800000",
                  seriesEndDt: "1653955200000",
                  isTimeAnnounced: true,
                  stateTitle: "CSK Won",
                },
                matchScore: {
                  team1Score: {
                    inngs1: {
                      inningsId: 1,
                      runs: 155,
                      wickets: 7,
                      overs: 19.6,
                    },
                  },
                  team2Score: {
                    inngs1: {
                      inningsId: 2,
                      runs: 156,
                      wickets: 7,
                      overs: 19.6,
                    },
                  },
                },
              },
            ],
          },
        },
        {
          adDetail: {
            name: "native_matches",
            layout: "native_large",
            position: 1,
          },
        },
      ],
    },
    {
      matchType: "Domestic",
      seriesMatches: [
        {
          seriesAdWrapper: {
            seriesId: 4011,
            seriesName: "County Championship Division One 2022",
            matches: [
              {
                matchInfo: {
                  matchId: 44271,
                  seriesId: 4011,
                  seriesName: "County Championship Division One 2022",
                  matchDesc: "County Div 1",
                  matchFormat: "TEST",
                  startDate: "1650535200000",
                  endDate: "1650819600000",
                  state: "Stumps",
                  status: "Day 1: Stumps",
                  team1: {
                    teamId: 150,
                    teamName: "Kent",
                    teamSName: "KENT",
                    imageId: 172217,
                  },
                  team2: {
                    teamId: 153,
                    teamName: "Hampshire",
                    teamSName: "HAM",
                    imageId: 172220,
                  },
                  venueInfo: {
                    id: 67,
                    ground: "St Lawrence Ground",
                    city: "Canterbury",
                    timezone: "+01:00",
                  },
                  currBatTeamId: 150,
                  seriesStartDt: "1649289600000",
                  seriesEndDt: "1664582400000",
                  isTimeAnnounced: true,
                  stateTitle: "Stumps",
                },
                matchScore: {
                  team1Score: {
                    inngs1: {
                      inningsId: 1,
                      runs: 271,
                      wickets: 7,
                      overs: 95.6,
                    },
                  },
                  team2Score: {},
                },
              },
              {
                matchInfo: {
                  matchId: 44291,
                  seriesId: 4011,
                  seriesName: "County Championship Division One 2022",
                  matchDesc: "County Div 1",
                  matchFormat: "TEST",
                  startDate: "1650535200000",
                  endDate: "1650819600000",
                  state: "Stumps",
                  status: "Day 1: Stumps - Warwickshire trail by 92 runs",
                  team1: {
                    teamId: 152,
                    teamName: "Essex",
                    teamSName: "ESS",
                    imageId: 172219,
                  },
                  team2: {
                    teamId: 140,
                    teamName: "Warwickshire",
                    teamSName: "WARKS",
                    imageId: 172207,
                  },
                  venueInfo: {
                    id: 20,
                    ground: "Edgbaston",
                    city: "Birmingham",
                    timezone: "+01:00",
                  },
                  currBatTeamId: 140,
                  seriesStartDt: "1649289600000",
                  seriesEndDt: "1664582400000",
                  isTimeAnnounced: true,
                  stateTitle: "Stumps",
                },
                matchScore: {
                  team1Score: {
                    inngs1: {
                      inningsId: 1,
                      runs: 168,
                      wickets: 10,
                      overs: 64.2,
                    },
                  },
                  team2Score: {
                    inngs1: {
                      inningsId: 2,
                      runs: 76,
                      wickets: 2,
                      overs: 30.6,
                    },
                  },
                },
              },
              {
                matchInfo: {
                  matchId: 44276,
                  seriesId: 4011,
                  seriesName: "County Championship Division One 2022",
                  matchDesc: "County Div 1",
                  matchFormat: "TEST",
                  startDate: "1650535200000",
                  endDate: "1650819600000",
                  state: "Stumps",
                  status: "Day 1: Stumps - Lancashire trail by 241 runs",
                  team1: {
                    teamId: 151,
                    teamName: "Gloucestershire",
                    teamSName: "GLOUCS",
                    imageId: 172218,
                  },
                  team2: {
                    teamId: 143,
                    teamName: "Lancashire",
                    teamSName: "LANCS",
                    imageId: 172210,
                  },
                  venueInfo: {
                    id: 65,
                    ground: "Emirates Old Trafford",
                    city: "Manchester",
                    timezone: "+01:00",
                  },
                  currBatTeamId: 143,
                  seriesStartDt: "1649289600000",
                  seriesEndDt: "1664582400000",
                  isTimeAnnounced: true,
                  stateTitle: "Stumps",
                },
                matchScore: {
                  team1Score: {
                    inngs1: {
                      inningsId: 1,
                      runs: 252,
                      wickets: 10,
                      overs: 87.6,
                    },
                  },
                  team2Score: {
                    inngs1: {
                      inningsId: 2,
                      runs: 11,
                      wickets: 1,
                      overs: 5.2,
                    },
                  },
                },
              },
              {
                matchInfo: {
                  matchId: 44281,
                  seriesId: 4011,
                  seriesName: "County Championship Division One 2022",
                  matchDesc: "County Div 1",
                  matchFormat: "TEST",
                  startDate: "1650535200000",
                  endDate: "1650819600000",
                  state: "Stumps",
                  status: "Day 1: Stumps - Northamptonshire trail by 270 runs",
                  team1: {
                    teamId: 146,
                    teamName: "Yorkshire",
                    teamSName: "YORKS",
                    imageId: 172213,
                  },
                  team2: {
                    teamId: 142,
                    teamName: "Northamptonshire",
                    teamSName: "NOR",
                    imageId: 172209,
                  },
                  venueInfo: {
                    id: 119,
                    ground: "County Ground",
                    city: "Northampton",
                    timezone: "+01:00",
                  },
                  currBatTeamId: 142,
                  seriesStartDt: "1649289600000",
                  seriesEndDt: "1664582400000",
                  isTimeAnnounced: true,
                  stateTitle: "Stumps",
                },
                matchScore: {
                  team1Score: {
                    inngs1: {
                      inningsId: 1,
                      runs: 296,
                      wickets: 10,
                      overs: 78.3,
                    },
                  },
                  team2Score: {
                    inngs1: {
                      inningsId: 2,
                      runs: 26,
                      wickets: 2,
                      overs: 14.6,
                    },
                  },
                },
              },
              {
                matchInfo: {
                  matchId: 44286,
                  seriesId: 4011,
                  seriesName: "County Championship Division One 2022",
                  matchDesc: "County Div 1",
                  matchFormat: "TEST",
                  startDate: "1650535200000",
                  endDate: "1650819600000",
                  state: "Stumps",
                  status: "Day 1: Stumps",
                  team1: {
                    teamId: 119,
                    teamName: "Somerset",
                    teamSName: "SOM",
                    imageId: 172199,
                  },
                  team2: {
                    teamId: 148,
                    teamName: "Surrey",
                    teamSName: "SUR",
                    imageId: 172215,
                  },
                  venueInfo: {
                    id: 12,
                    ground: "Kennington Oval",
                    city: "London",
                    timezone: "+01:00",
                  },
                  currBatTeamId: 119,
                  seriesStartDt: "1649289600000",
                  seriesEndDt: "1664582400000",
                  isTimeAnnounced: true,
                  stateTitle: "Stumps",
                },
                matchScore: {
                  team1Score: {
                    inngs1: {
                      inningsId: 1,
                      runs: 283,
                      wickets: 6,
                      overs: 95.6,
                    },
                  },
                  team2Score: {},
                },
              },
            ],
          },
        },
        {
          seriesAdWrapper: {
            seriesId: 4016,
            seriesName: "County Championship Division Two 2022",
            matches: [
              {
                matchInfo: {
                  matchId: 44631,
                  seriesId: 4016,
                  seriesName: "County Championship Division Two 2022",
                  matchDesc: "County Div 2",
                  matchFormat: "TEST",
                  startDate: "1650535200000",
                  endDate: "1650819600000",
                  state: "Stumps",
                  status: "Day 1: Stumps",
                  team1: {
                    teamId: 147,
                    teamName: "Worcestershire",
                    teamSName: "WORCS",
                    imageId: 172214,
                  },
                  team2: {
                    teamId: 41,
                    teamName: "Sussex",
                    teamSName: "SUS",
                    imageId: 172148,
                  },
                  venueInfo: {
                    id: 225,
                    ground: "New Road",
                    city: "Worcester",
                    timezone: "+01:00",
                  },
                  currBatTeamId: 147,
                  seriesStartDt: "1649289600000",
                  seriesEndDt: "1664582400000",
                  isTimeAnnounced: true,
                  stateTitle: "Stumps",
                },
                matchScore: {
                  team1Score: {
                    inngs1: {
                      inningsId: 1,
                      runs: 338,
                      wickets: 5,
                      overs: 95.6,
                    },
                  },
                  team2Score: {},
                },
              },
              {
                matchInfo: {
                  matchId: 44616,
                  seriesId: 4016,
                  seriesName: "County Championship Division Two 2022",
                  matchDesc: "County Div 2",
                  matchFormat: "TEST",
                  startDate: "1650535200000",
                  endDate: "1650819600000",
                  state: "Stumps",
                  status: "Day 1: Stumps - Nottinghamshire trail by 180 runs",
                  team1: {
                    teamId: 141,
                    teamName: "Durham",
                    teamSName: "DUR",
                    imageId: 172208,
                  },
                  team2: {
                    teamId: 139,
                    teamName: "Nottinghamshire",
                    teamSName: "NOTTS",
                    imageId: 172206,
                  },
                  venueInfo: {
                    id: 60,
                    ground: "Riverside Ground",
                    city: "Chester-le-Street",
                    timezone: "+01:00",
                  },
                  currBatTeamId: 139,
                  seriesStartDt: "1649289600000",
                  seriesEndDt: "1664582400000",
                  isTimeAnnounced: true,
                  stateTitle: "Stumps",
                },
                matchScore: {
                  team1Score: {
                    inngs1: {
                      inningsId: 1,
                      runs: 230,
                      wickets: 10,
                      overs: 78.4,
                    },
                  },
                  team2Score: {
                    inngs1: {
                      inningsId: 2,
                      runs: 50,
                      overs: 14.6,
                    },
                  },
                },
              },
              {
                matchInfo: {
                  matchId: 44621,
                  seriesId: 4016,
                  seriesName: "County Championship Division Two 2022",
                  matchDesc: "County Div 2",
                  matchFormat: "TEST",
                  startDate: "1650535200000",
                  endDate: "1650819600000",
                  state: "Stumps",
                  status: "Day 1: Stumps - Middlesex lead by 49 runs",
                  team1: {
                    teamId: 149,
                    teamName: "Glamorgan",
                    teamSName: "GLAM",
                    imageId: 172216,
                  },
                  team2: {
                    teamId: 74,
                    teamName: "Middlesex",
                    teamSName: "MDX",
                    imageId: 172170,
                  },
                  venueInfo: {
                    id: 62,
                    ground: "Sophia Gardens",
                    city: "Cardiff",
                    timezone: "+01:00",
                  },
                  currBatTeamId: 74,
                  seriesStartDt: "1649289600000",
                  seriesEndDt: "1664582400000",
                  isTimeAnnounced: true,
                  stateTitle: "Stumps",
                },
                matchScore: {
                  team1Score: {
                    inngs1: {
                      inningsId: 1,
                      runs: 122,
                      wickets: 10,
                      overs: 41.1,
                    },
                  },
                  team2Score: {
                    inngs1: {
                      inningsId: 2,
                      runs: 171,
                      wickets: 6,
                      overs: 51.6,
                    },
                  },
                },
              },
              {
                matchInfo: {
                  matchId: 44626,
                  seriesId: 4016,
                  seriesName: "County Championship Division Two 2022",
                  matchDesc: "County Div 2",
                  matchFormat: "TEST",
                  startDate: "1650535200000",
                  endDate: "1650819600000",
                  state: "Stumps",
                  status: "Day 1: Stumps - Derbyshire trail by 177 runs",
                  team1: {
                    teamId: 145,
                    teamName: "Leicestershire",
                    teamSName: "LEIC",
                    imageId: 172212,
                  },
                  team2: {
                    teamId: 144,
                    teamName: "Derbyshire",
                    teamSName: "DERBY",
                    imageId: 172211,
                  },
                  venueInfo: {
                    id: 222,
                    ground: "Grace Road",
                    city: "Leicester",
                    timezone: "+01:00",
                  },
                  currBatTeamId: 144,
                  seriesStartDt: "1649289600000",
                  seriesEndDt: "1664582400000",
                  isTimeAnnounced: true,
                  stateTitle: "Stumps",
                },
                matchScore: {
                  team1Score: {
                    inngs1: {
                      inningsId: 1,
                      runs: 213,
                      wickets: 10,
                      overs: 77.2,
                    },
                  },
                  team2Score: {
                    inngs1: {
                      inningsId: 2,
                      runs: 36,
                      wickets: 1,
                      overs: 15.6,
                    },
                  },
                },
              },
            ],
          },
        },
      ],
    },
    {
      matchType: "Women",
      seriesMatches: [
        {
          seriesAdWrapper: {
            seriesId: 4147,
            seriesName: "Capricorn Womens Tri-Series, 2022",
            matches: [
              {
                matchInfo: {
                  matchId: 47134,
                  seriesId: 4147,
                  seriesName: "Capricorn Womens Tri-Series, 2022",
                  matchDesc: "3rd Match",
                  matchFormat: "T20",
                  startDate: "1650544200000",
                  endDate: "1650556800000",
                  state: "Complete",
                  status: "Zimbabwe Women won by 8 runs",
                  team1: {
                    teamId: 388,
                    teamName: "Zimbabwe Women",
                    teamSName: "ZIMW",
                    imageId: 172441,
                  },
                  team2: {
                    teamId: 448,
                    teamName: "Uganda Women",
                    teamSName: "UGAW",
                    imageId: 172496,
                  },
                  venueInfo: {
                    id: 899,
                    ground: "Centre for Cricket Development Ground",
                    city: "Windhoek",
                    timezone: "+02:00",
                  },
                  currBatTeamId: 388,
                  seriesStartDt: "1650412800000",
                  seriesEndDt: "1651104000000",
                  isTimeAnnounced: true,
                  stateTitle: "ZIMW Won",
                },
                matchScore: {
                  team1Score: {
                    inngs1: {
                      inningsId: 1,
                      runs: 100,
                      wickets: 10,
                      overs: 19.5,
                    },
                  },
                  team2Score: {
                    inngs1: {
                      inningsId: 2,
                      runs: 92,
                      wickets: 8,
                      overs: 20,
                    },
                  },
                },
              },
            ],
          },
        },
      ],
    },
  ],
  filters: {
    matchType: ["International", "League", "Domestic", "Women"],
  },
  appIndex: {
    seoTitle: "Live Cricket Score - Scorecard and Match Results",
    webURL: "www.cricbuzz.com/live-cricket-scores/",
  },
  responseLastUpdated: "1650567435",
};

export const scoreCardDetails = {
  scoreCard: [
    {
      matchId: 40381,
      inningsId: 1,
      timeScore: 1640309044000,
      batTeamDetails: {
        batTeamId: 27,
        batTeamName: "Ireland",
        batTeamShortName: "IRE",
        batsmenData: {
          bat_5: {
            batId: 6471,
            batName: "Getkate",
            batShortName: "",
            isCaptain: false,
            isKeeper: false,
            runs: 5,
            balls: 10,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 50,
            outDesc: "c Ritwik Behera       b Vatsal Vaghela",
            bowlerId: 22531,
            fielderId1: 22891,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 0,
            sixers: 0,
            wicketCode: "CAUGHT",
          },
          bat_2: {
            batId: 6710,
            batName: "Balbirnie",
            batShortName: "",
            isCaptain: true,
            isKeeper: false,
            runs: 10,
            balls: 5,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 200,
            outDesc: "c Sushant Modani       b Netravalkar",
            bowlerId: 9748,
            fielderId1: 20217,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 2,
            sixers: 0,
            wicketCode: "CAUGHT",
          },
          bat_10: {
            batId: 10451,
            batName: "Barry McCarthy",
            batShortName: "",
            isCaptain: false,
            isKeeper: false,
            runs: 0,
            balls: 1,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 0,
            outDesc: "run out (Monank Patel) ",
            bowlerId: 0,
            fielderId1: 14732,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 0,
            sixers: 0,
            wicketCode: "RUNOUT",
          },
          bat_7: {
            batId: 11129,
            batName: "William McClintock",
            batShortName: "",
            isCaptain: false,
            isKeeper: false,
            runs: 1,
            balls: 3,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 33.33,
            outDesc: "c Marty Kain       b Nisarg Patel",
            bowlerId: 15475,
            fielderId1: 10699,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 0,
            sixers: 0,
            wicketCode: "CAUGHT",
          },
          bat_1: {
            batId: 1114,
            batName: "Stirling",
            batShortName: "",
            isCaptain: false,
            isKeeper: false,
            runs: 5,
            balls: 5,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 100,
            outDesc: "lbw       b Nisarg Patel",
            bowlerId: 15475,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 1,
            sixers: 0,
            wicketCode: "LBW",
          },
          bat_8: {
            batId: 10449,
            batName: "Mark Adair",
            batShortName: "",
            isCaptain: false,
            isKeeper: false,
            runs: 3,
            balls: 4,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 75,
            outDesc: "       b Netravalkar",
            bowlerId: 9748,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 0,
            sixers: 0,
            wicketCode: "BOWLED",
          },
          bat_3: {
            batId: 11131,
            batName: "Lorcan Tucker",
            batShortName: "",
            isCaptain: false,
            isKeeper: false,
            runs: 84,
            balls: 56,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 150,
            outDesc: "       b Netravalkar",
            bowlerId: 9748,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 9,
            sixers: 3,
            wicketCode: "BOWLED",
          },
          bat_9: {
            batId: 12769,
            batName: "Simi Singh",
            batShortName: "",
            isCaptain: false,
            isKeeper: false,
            runs: 13,
            balls: 11,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 118.18,
            outDesc: "c Ali Khan       b Yasir Mohammad",
            bowlerId: 22901,
            fielderId1: 11450,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 1,
            sixers: 0,
            wicketCode: "CAUGHT",
          },
          bat_6: {
            batId: 13309,
            batName: "Neil Rock",
            batShortName: "",
            isCaptain: false,
            isKeeper: true,
            runs: 4,
            balls: 5,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 80,
            outDesc: "c Ritwik Behera       b Vatsal Vaghela",
            bowlerId: 22531,
            fielderId1: 22891,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 0,
            sixers: 0,
            wicketCode: "CAUGHT",
          },
          bat_4: {
            batId: 18143,
            batName: "Curtis Campher",
            batShortName: "",
            isCaptain: false,
            isKeeper: false,
            runs: 17,
            balls: 11,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 154.55,
            outDesc: "c Marty Kain       b Yasir Mohammad",
            bowlerId: 22901,
            fielderId1: 10699,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 2,
            sixers: 1,
            wicketCode: "CAUGHT",
          },
          bat_11: {
            batId: 11124,
            batName: "Benjamin White",
            batShortName: "",
            isCaptain: false,
            isKeeper: false,
            runs: 2,
            balls: 2,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 100,
            outDesc: "not out",
            bowlerId: 0,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 0,
            sixers: 0,
            wicketCode: "",
          },
        },
      },
      bowlTeamDetails: {
        bowlTeamId: 15,
        bowlTeamName: "United States",
        bowlTeamShortName: "USA",
        bowlersData: {
          bowl_1: {
            bowlerId: 15475,
            bowlName: "Nisarg Patel",
            bowlShortName: "",
            isCaptain: false,
            isKeeper: false,
            overs: 4,
            maidens: 0,
            runs: 29,
            wickets: 2,
            economy: 7.2,
            no_balls: 0,
            wides: 0,
            dots: 0,
            balls: 40,
            runsPerBall: 0.73,
          },
          bowl_4: {
            bowlerId: 22901,
            bowlName: "Yasir Mohammad",
            bowlShortName: "",
            isCaptain: false,
            isKeeper: false,
            overs: 4,
            maidens: 0,
            runs: 32,
            wickets: 2,
            economy: 8,
            no_balls: 0,
            wides: 5,
            dots: 0,
            balls: 40,
            runsPerBall: 0.8,
          },
          bowl_6: {
            bowlerId: 22891,
            bowlName: "Ritwik Behera",
            bowlShortName: "",
            isCaptain: false,
            isKeeper: false,
            overs: 1,
            maidens: 0,
            runs: 5,
            wickets: 0,
            economy: 5,
            no_balls: 0,
            wides: 0,
            dots: 0,
            balls: 10,
            runsPerBall: 0.5,
          },
          bowl_5: {
            bowlerId: 22531,
            bowlName: "Vatsal Vaghela",
            bowlShortName: "",
            isCaptain: false,
            isKeeper: false,
            overs: 3,
            maidens: 0,
            runs: 16,
            wickets: 2,
            economy: 5.3,
            no_balls: 0,
            wides: 0,
            dots: 0,
            balls: 30,
            runsPerBall: 0.53,
          },
          bowl_3: {
            bowlerId: 11450,
            bowlName: "Ali Khan",
            bowlShortName: "",
            isCaptain: false,
            isKeeper: false,
            overs: 3,
            maidens: 0,
            runs: 34,
            wickets: 0,
            economy: 11.3,
            no_balls: 0,
            wides: 0,
            dots: 0,
            balls: 30,
            runsPerBall: 1.13,
          },
          bowl_2: {
            bowlerId: 9748,
            bowlName: "Netravalkar",
            bowlShortName: "",
            isCaptain: false,
            isKeeper: false,
            overs: 3.5,
            maidens: 0,
            runs: 33,
            wickets: 3,
            economy: 8.6,
            no_balls: 0,
            wides: 0,
            dots: 0,
            balls: 35,
            runsPerBall: 0.94,
          },
        },
      },
      scoreDetails: {
        ballNbr: 113,
        isDeclared: false,
        isFollowOn: false,
        overs: 18.5,
        revisedOvers: 0,
        runRate: 7.96,
        runs: 150,
        wickets: 10,
        runsPerBall: 0.81,
      },
      extrasData: {
        noBalls: 0,
        total: 6,
        byes: 0,
        penalty: 0,
        wides: 5,
        legByes: 1,
      },
      ppData: {},
      wicketsData: {
        wkt_8: {
          batId: 12769,
          batName: "Simi Singh",
          wktNbr: 8,
          wktOver: 16.5,
          wktRuns: 128,
          ballNbr: 165,
        },
        wkt_2: {
          batId: 6710,
          batName: "Balbirnie",
          wktNbr: 2,
          wktOver: 1.6,
          wktRuns: 20,
          ballNbr: 16,
        },
        wkt_9: {
          batId: 10451,
          batName: "Barry McCarthy",
          wktNbr: 9,
          wktOver: 17.3,
          wktRuns: 134,
          ballNbr: 173,
        },
        wkt_1: {
          batId: 1114,
          batName: "Stirling",
          wktNbr: 1,
          wktOver: 0.6,
          wktRuns: 6,
          ballNbr: 6,
        },
        wkt_6: {
          batId: 11129,
          batName: "William McClintock",
          wktNbr: 6,
          wktOver: 12.4,
          wktRuns: 96,
          ballNbr: 124,
        },
        wkt_10: {
          batId: 11131,
          batName: "Lorcan Tucker",
          wktNbr: 10,
          wktOver: 18.5,
          wktRuns: 150,
          ballNbr: 185,
        },
        wkt_4: {
          batId: 6471,
          batName: "Getkate",
          wktNbr: 4,
          wktOver: 9.5,
          wktRuns: 83,
          ballNbr: 95,
        },
        wkt_5: {
          batId: 13309,
          batName: "Neil Rock",
          wktNbr: 5,
          wktOver: 11.4,
          wktRuns: 92,
          ballNbr: 114,
        },
        wkt_7: {
          batId: 10449,
          batName: "Mark Adair",
          wktNbr: 7,
          wktOver: 13.5,
          wktRuns: 102,
          ballNbr: 135,
        },
        wkt_3: {
          batId: 18143,
          batName: "Curtis Campher",
          wktNbr: 3,
          wktOver: 6.1,
          wktRuns: 59,
          ballNbr: 61,
        },
      },
      partnershipsData: {
        pat_10: {
          bat1Id: 11131,
          bat1Name: "Lorcan Tucker",
          bat1Runs: 14,
          bat1fours: 2,
          bat1sixes: 1,
          bat2Id: 11124,
          bat2Name: "Benjamin White",
          bat2Runs: 2,
          bat2fours: 0,
          bat2sixes: 0,
          totalRuns: 16,
          totalBalls: 8,
          bat1balls: 0,
          bat2balls: 0,
          bat1Ones: 0,
          bat1Twos: 0,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 0,
          bat1Sixers: 0,
          bat2Ones: 0,
          bat2Twos: 0,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 0,
          bat2Sixers: 0,
        },
        pat_1: {
          bat1Id: 1114,
          bat1Name: "Stirling",
          bat1Runs: 5,
          bat1fours: 1,
          bat1sixes: 0,
          bat2Id: 6710,
          bat2Name: "Balbirnie",
          bat2Runs: 1,
          bat2fours: 0,
          bat2sixes: 0,
          totalRuns: 6,
          totalBalls: 6,
          bat1balls: 0,
          bat2balls: 0,
          bat1Ones: 0,
          bat1Twos: 0,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 0,
          bat1Sixers: 0,
          bat2Ones: 0,
          bat2Twos: 0,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 0,
          bat2Sixers: 0,
        },
        pat_6: {
          bat1Id: 11131,
          bat1Name: "Lorcan Tucker",
          bat1Runs: 3,
          bat1fours: 0,
          bat1sixes: 0,
          bat2Id: 11129,
          bat2Name: "William McClintock",
          bat2Runs: 1,
          bat2fours: 0,
          bat2sixes: 0,
          totalRuns: 4,
          totalBalls: 6,
          bat1balls: 0,
          bat2balls: 0,
          bat1Ones: 0,
          bat1Twos: 0,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 0,
          bat1Sixers: 0,
          bat2Ones: 0,
          bat2Twos: 0,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 0,
          bat2Sixers: 0,
        },
        pat_9: {
          bat1Id: 11131,
          bat1Name: "Lorcan Tucker",
          bat1Runs: 6,
          bat1fours: 0,
          bat1sixes: 1,
          bat2Id: 10451,
          bat2Name: "McCarthy",
          bat2Runs: 0,
          bat2fours: 0,
          bat2sixes: 0,
          totalRuns: 6,
          totalBalls: 4,
          bat1balls: 0,
          bat2balls: 0,
          bat1Ones: 0,
          bat1Twos: 0,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 0,
          bat1Sixers: 0,
          bat2Ones: 0,
          bat2Twos: 0,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 0,
          bat2Sixers: 0,
        },
        pat_2: {
          bat1Id: 11131,
          bat1Name: "Lorcan Tucker",
          bat1Runs: 5,
          bat1fours: 1,
          bat1sixes: 0,
          bat2Id: 6710,
          bat2Name: "Balbirnie",
          bat2Runs: 9,
          bat2fours: 2,
          bat2sixes: 0,
          totalRuns: 14,
          totalBalls: 6,
          bat1balls: 0,
          bat2balls: 0,
          bat1Ones: 0,
          bat1Twos: 0,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 0,
          bat1Sixers: 0,
          bat2Ones: 0,
          bat2Twos: 0,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 0,
          bat2Sixers: 0,
        },
        pat_5: {
          bat1Id: 11131,
          bat1Name: "Lorcan Tucker",
          bat1Runs: 5,
          bat1fours: 0,
          bat1sixes: 0,
          bat2Id: 13309,
          bat2Name: "Neil Rock",
          bat2Runs: 4,
          bat2fours: 0,
          bat2sixes: 0,
          totalRuns: 9,
          totalBalls: 11,
          bat1balls: 0,
          bat2balls: 0,
          bat1Ones: 0,
          bat1Twos: 0,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 0,
          bat1Sixers: 0,
          bat2Ones: 0,
          bat2Twos: 0,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 0,
          bat2Sixers: 0,
        },
        pat_3: {
          bat1Id: 11131,
          bat1Name: "Lorcan Tucker",
          bat1Runs: 22,
          bat1fours: 3,
          bat1sixes: 1,
          bat2Id: 18143,
          bat2Name: "Curtis Campher",
          bat2Runs: 17,
          bat2fours: 2,
          bat2sixes: 1,
          totalRuns: 39,
          totalBalls: 25,
          bat1balls: 0,
          bat2balls: 0,
          bat1Ones: 0,
          bat1Twos: 0,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 0,
          bat1Sixers: 0,
          bat2Ones: 0,
          bat2Twos: 0,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 0,
          bat2Sixers: 0,
        },
        pat_8: {
          bat1Id: 11131,
          bat1Name: "Lorcan Tucker",
          bat1Runs: 7,
          bat1fours: 0,
          bat1sixes: 0,
          bat2Id: 12769,
          bat2Name: "Simi Singh",
          bat2Runs: 13,
          bat2fours: 1,
          bat2sixes: 0,
          totalRuns: 26,
          totalBalls: 18,
          bat1balls: 0,
          bat2balls: 0,
          bat1Ones: 0,
          bat1Twos: 0,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 0,
          bat1Sixers: 0,
          bat2Ones: 0,
          bat2Twos: 0,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 0,
          bat2Sixers: 0,
        },
        pat_4: {
          bat1Id: 11131,
          bat1Name: "Lorcan Tucker",
          bat1Runs: 19,
          bat1fours: 3,
          bat1sixes: 0,
          bat2Id: 6471,
          bat2Name: "Getkate",
          bat2Runs: 5,
          bat2fours: 0,
          bat2sixes: 0,
          totalRuns: 24,
          totalBalls: 22,
          bat1balls: 0,
          bat2balls: 0,
          bat1Ones: 0,
          bat1Twos: 0,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 0,
          bat1Sixers: 0,
          bat2Ones: 0,
          bat2Twos: 0,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 0,
          bat2Sixers: 0,
        },
        pat_7: {
          bat1Id: 11131,
          bat1Name: "Lorcan Tucker",
          bat1Runs: 3,
          bat1fours: 0,
          bat1sixes: 0,
          bat2Id: 10449,
          bat2Name: "Mark Adair",
          bat2Runs: 3,
          bat2fours: 0,
          bat2sixes: 0,
          totalRuns: 6,
          totalBalls: 7,
          bat1balls: 0,
          bat2balls: 0,
          bat1Ones: 0,
          bat1Twos: 0,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 0,
          bat1Sixers: 0,
          bat2Ones: 0,
          bat2Twos: 0,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 0,
          bat2Sixers: 0,
        },
      },
    },
    {
      matchId: 40381,
      inningsId: 2,
      timeScore: 1640316185000,
      batTeamDetails: {
        batTeamId: 15,
        batTeamName: "United States",
        batTeamShortName: "USA",
        batsmenData: {
          bat_5: {
            batId: 20217,
            batName: "Sushant Modani",
            batShortName: "Sushant Modani",
            isCaptain: false,
            isKeeper: false,
            runs: 27,
            balls: 16,
            dots: 3,
            fours: 1,
            sixes: 2,
            mins: 22,
            strikeRate: 168.75,
            outDesc: "c Lorcan Tucker       b Curtis Campher",
            bowlerId: 18143,
            fielderId1: 11131,
            fielderId2: 0,
            fielderId3: 0,
            ones: 9,
            twos: 1,
            threes: 0,
            fives: 0,
            boundaries: 1,
            sixers: 2,
            wicketCode: "CAUGHT",
          },
          bat_2: {
            batId: 22896,
            batName: "Ryan Scott",
            batShortName: "Ryan Scott",
            isCaptain: false,
            isKeeper: false,
            runs: 11,
            balls: 11,
            dots: 7,
            fours: 2,
            sixes: 0,
            mins: 11,
            strikeRate: 100,
            outDesc: "run out (Curtis Campher) ",
            bowlerId: 0,
            fielderId1: 18143,
            fielderId2: 0,
            fielderId3: 0,
            ones: 1,
            twos: 1,
            threes: 0,
            fives: 0,
            boundaries: 2,
            sixers: 0,
            wicketCode: "RUNOUT",
          },
          bat_10: {
            batId: 22531,
            batName: "Vatsal Vaghela",
            batShortName: "Vatsal Vaghela",
            isCaptain: false,
            isKeeper: false,
            runs: 0,
            balls: 0,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 0,
            outDesc: "",
            bowlerId: 0,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 0,
            sixers: 0,
            wicketCode: "",
          },
          bat_7: {
            batId: 15475,
            batName: "Nisarg Patel",
            batShortName: "Nisarg Patel",
            isCaptain: false,
            isKeeper: false,
            runs: 10,
            balls: 6,
            dots: 2,
            fours: 2,
            sixes: 0,
            mins: 14,
            strikeRate: 166.67,
            outDesc: "not out",
            bowlerId: 0,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 2,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 2,
            sixers: 0,
            wicketCode: "",
          },
          bat_1: {
            batId: 22891,
            batName: "Ritwik Behera",
            batShortName: "Ritwik Behera",
            isCaptain: false,
            isKeeper: false,
            runs: 16,
            balls: 23,
            dots: 13,
            fours: 1,
            sixes: 0,
            mins: 31,
            strikeRate: 69.57,
            outDesc: "c Getkate       b Mark Adair",
            bowlerId: 10449,
            fielderId1: 6471,
            fielderId2: 0,
            fielderId3: 0,
            ones: 6,
            twos: 3,
            threes: 0,
            fives: 0,
            boundaries: 1,
            sixers: 0,
            wicketCode: "CAUGHT",
          },
          bat_8: {
            batId: 22901,
            batName: "Yasir Mohammad",
            batShortName: "Yasir Mohammad",
            isCaptain: false,
            isKeeper: false,
            runs: 0,
            balls: 2,
            dots: 2,
            fours: 0,
            sixes: 0,
            mins: 1,
            strikeRate: 0,
            outDesc: "   c and b Curtis Campher",
            bowlerId: 18143,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 0,
            sixers: 0,
            wicketCode: "CAUGHTBOWLED",
          },
          bat_3: {
            batId: 14732,
            batName: "Monank Patel",
            batShortName: "Monank Patel",
            isCaptain: true,
            isKeeper: true,
            runs: 26,
            balls: 27,
            dots: 12,
            fours: 2,
            sixes: 1,
            mins: 35,
            strikeRate: 96.3,
            outDesc: "c Mark Adair       b Benjamin White",
            bowlerId: 11124,
            fielderId1: 10449,
            fielderId2: 0,
            fielderId3: 0,
            ones: 12,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 2,
            sixers: 1,
            wicketCode: "CAUGHT",
          },
          bat_9: {
            batId: 9748,
            batName: "Saurabh Netravalkar",
            batShortName: "Netravalkar",
            isCaptain: false,
            isKeeper: false,
            runs: 5,
            balls: 6,
            dots: 3,
            fours: 0,
            sixes: 0,
            mins: 11,
            strikeRate: 83.33,
            outDesc: "not out",
            bowlerId: 0,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 1,
            twos: 2,
            threes: 0,
            fives: 0,
            boundaries: 0,
            sixers: 0,
            wicketCode: "",
          },
          bat_6: {
            batId: 10699,
            batName: "Marty Kain",
            batShortName: "Marty Kain",
            isCaptain: false,
            isKeeper: false,
            runs: 11,
            balls: 11,
            dots: 5,
            fours: 1,
            sixes: 0,
            mins: 18,
            strikeRate: 100,
            outDesc: "       b Curtis Campher",
            bowlerId: 18143,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 3,
            twos: 2,
            threes: 0,
            fives: 0,
            boundaries: 1,
            sixers: 0,
            wicketCode: "BOWLED",
          },
          bat_4: {
            batId: 12788,
            batName: "Gajanand Singh",
            batShortName: "Gajanand Singh",
            isCaptain: false,
            isKeeper: false,
            runs: 22,
            balls: 20,
            dots: 6,
            fours: 1,
            sixes: 1,
            mins: 28,
            strikeRate: 110,
            outDesc: "lbw       b Curtis Campher",
            bowlerId: 18143,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 12,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 1,
            sixers: 1,
            wicketCode: "LBW",
          },
          bat_11: {
            batId: 11450,
            batName: "Ali Khan",
            batShortName: "Ali Khan",
            isCaptain: false,
            isKeeper: false,
            runs: 0,
            balls: 0,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 0,
            outDesc: "",
            bowlerId: 0,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 0,
            sixers: 0,
            wicketCode: "",
          },
        },
      },
      bowlTeamDetails: {
        bowlTeamId: 27,
        bowlTeamName: "Ireland",
        bowlTeamShortName: "IRE",
        bowlersData: {
          bowl_1: {
            bowlerId: 10449,
            bowlName: "Mark Adair",
            bowlShortName: "Mark Adair",
            isCaptain: false,
            isKeeper: false,
            overs: 4,
            maidens: 0,
            runs: 25,
            wickets: 1,
            economy: 6.2,
            no_balls: 0,
            wides: 2,
            dots: 0,
            balls: 40,
            runsPerBall: 0.63,
          },
          bowl_4: {
            bowlerId: 12769,
            bowlName: "Simi Singh",
            bowlShortName: "Simi Singh",
            isCaptain: false,
            isKeeper: false,
            overs: 4,
            maidens: 0,
            runs: 31,
            wickets: 0,
            economy: 7.8,
            no_balls: 0,
            wides: 0,
            dots: 0,
            balls: 40,
            runsPerBall: 0.78,
          },
          bowl_6: {
            bowlerId: 1114,
            bowlName: "Paul Stirling",
            bowlShortName: "Stirling",
            isCaptain: false,
            isKeeper: false,
            overs: 1,
            maidens: 0,
            runs: 4,
            wickets: 0,
            economy: 4,
            no_balls: 0,
            wides: 0,
            dots: 0,
            balls: 10,
            runsPerBall: 0.4,
          },
          bowl_5: {
            bowlerId: 11124,
            bowlName: "Benjamin White",
            bowlShortName: "Benjamin White",
            isCaptain: false,
            isKeeper: false,
            overs: 3,
            maidens: 0,
            runs: 27,
            wickets: 1,
            economy: 9,
            no_balls: 1,
            wides: 2,
            dots: 0,
            balls: 30,
            runsPerBall: 0.9,
          },
          bowl_3: {
            bowlerId: 18143,
            bowlName: "Curtis Campher",
            bowlShortName: "Curtis Campher",
            isCaptain: false,
            isKeeper: false,
            overs: 4,
            maidens: 1,
            runs: 25,
            wickets: 4,
            economy: 6.2,
            no_balls: 1,
            wides: 1,
            dots: 1,
            balls: 40,
            runsPerBall: 0.63,
          },
          bowl_2: {
            bowlerId: 10451,
            bowlName: "Barry McCarthy",
            bowlShortName: "Barry McCarthy",
            isCaptain: false,
            isKeeper: false,
            overs: 4,
            maidens: 0,
            runs: 24,
            wickets: 0,
            economy: 6,
            no_balls: 0,
            wides: 1,
            dots: 0,
            balls: 40,
            runsPerBall: 0.6,
          },
        },
      },
      scoreDetails: {
        ballNbr: 120,
        isDeclared: false,
        isFollowOn: false,
        overs: 20,
        revisedOvers: 0,
        runRate: 7.05,
        runs: 141,
        wickets: 7,
        runsPerBall: 0.71,
      },
      extrasData: {
        noBalls: 2,
        total: 13,
        byes: 1,
        penalty: 0,
        wides: 6,
        legByes: 4,
      },
      ppData: {},
      wicketsData: {
        wkt_2: {
          batId: 22891,
          batName: "Ritwik Behera",
          wktNbr: 2,
          wktOver: 7.2,
          wktRuns: 40,
          ballNbr: 72,
        },
        wkt_1: {
          batId: 22896,
          batName: "Ryan Scott",
          wktNbr: 1,
          wktOver: 3,
          wktRuns: 20,
          ballNbr: 30,
        },
        wkt_6: {
          batId: 10699,
          batName: "Marty Kain",
          wktNbr: 6,
          wktOver: 17.4,
          wktRuns: 122,
          ballNbr: 174,
        },
        wkt_4: {
          batId: 12788,
          batName: "Gajanand Singh",
          wktNbr: 4,
          wktOver: 14.3,
          wktRuns: 89,
          ballNbr: 143,
        },
        wkt_5: {
          batId: 20217,
          batName: "Sushant Modani",
          wktNbr: 5,
          wktOver: 17.3,
          wktRuns: 122,
          ballNbr: 173,
        },
        wkt_7: {
          batId: 22901,
          batName: "Yasir Mohammad",
          wktNbr: 7,
          wktOver: 17.6,
          wktRuns: 123,
          ballNbr: 176,
        },
        wkt_3: {
          batId: 14732,
          batName: "Monank Patel",
          wktNbr: 3,
          wktOver: 11.4,
          wktRuns: 68,
          ballNbr: 114,
        },
      },
      partnershipsData: {
        pat_1: {
          bat1Id: 22891,
          bat1Name: "Ritwik Behera",
          bat1Runs: 6,
          bat1fours: 0,
          bat1sixes: 0,
          bat2Id: 22896,
          bat2Name: "Ryan Scott",
          bat2Runs: 11,
          bat2fours: 2,
          bat2sixes: 0,
          totalRuns: 20,
          totalBalls: 18,
          bat1balls: 7,
          bat2balls: 11,
          bat1Ones: 2,
          bat1Twos: 2,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 0,
          bat1Sixers: 0,
          bat2Ones: 1,
          bat2Twos: 1,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 2,
          bat2Sixers: 0,
        },
        pat_6: {
          bat1Id: 10699,
          bat1Name: "Marty Kain",
          bat1Runs: 0,
          bat1fours: 0,
          bat1sixes: 0,
          bat2Id: 15475,
          bat2Name: "Nisarg Patel",
          bat2Runs: 0,
          bat2fours: 0,
          bat2sixes: 0,
          totalRuns: 0,
          totalBalls: 1,
          bat1balls: 1,
          bat2balls: 0,
          bat1Ones: 0,
          bat1Twos: 0,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 0,
          bat1Sixers: 0,
          bat2Ones: 0,
          bat2Twos: 0,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 0,
          bat2Sixers: 0,
        },
        pat_2: {
          bat1Id: 22891,
          bat1Name: "Ritwik Behera",
          bat1Runs: 10,
          bat1fours: 1,
          bat1sixes: 0,
          bat2Id: 14732,
          bat2Name: "Monank Patel",
          bat2Runs: 10,
          bat2fours: 1,
          bat2sixes: 0,
          totalRuns: 20,
          totalBalls: 26,
          bat1balls: 16,
          bat2balls: 10,
          bat1Ones: 4,
          bat1Twos: 1,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 1,
          bat1Sixers: 0,
          bat2Ones: 6,
          bat2Twos: 0,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 1,
          bat2Sixers: 0,
        },
        pat_5: {
          bat1Id: 10699,
          bat1Name: "Marty Kain",
          bat1Runs: 11,
          bat1fours: 1,
          bat1sixes: 0,
          bat2Id: 20217,
          bat2Name: "Sushant Modani",
          bat2Runs: 20,
          bat2fours: 1,
          bat2sixes: 2,
          totalRuns: 33,
          totalBalls: 19,
          bat1balls: 10,
          bat2balls: 9,
          bat1Ones: 3,
          bat1Twos: 2,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 1,
          bat1Sixers: 0,
          bat2Ones: 4,
          bat2Twos: 0,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 1,
          bat2Sixers: 2,
        },
        pat_3: {
          bat1Id: 12788,
          bat1Name: "Gajanand",
          bat1Runs: 8,
          bat1fours: 0,
          bat1sixes: 0,
          bat2Id: 14732,
          bat2Name: "Monank Patel",
          bat2Runs: 16,
          bat2fours: 1,
          bat2sixes: 1,
          totalRuns: 28,
          totalBalls: 27,
          bat1balls: 10,
          bat2balls: 17,
          bat1Ones: 8,
          bat1Twos: 0,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 0,
          bat1Sixers: 0,
          bat2Ones: 6,
          bat2Twos: 0,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 1,
          bat2Sixers: 1,
        },
        pat_8: {
          bat1Id: 9748,
          bat1Name: "Netravalkar",
          bat1Runs: 5,
          bat1fours: 0,
          bat1sixes: 0,
          bat2Id: 15475,
          bat2Name: "Nisarg Patel",
          bat2Runs: 10,
          bat2fours: 2,
          bat2sixes: 0,
          totalRuns: 18,
          totalBalls: 12,
          bat1balls: 6,
          bat2balls: 6,
          bat1Ones: 1,
          bat1Twos: 2,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 0,
          bat1Sixers: 0,
          bat2Ones: 2,
          bat2Twos: 0,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 2,
          bat2Sixers: 0,
        },
        pat_4: {
          bat1Id: 12788,
          bat1Name: "Gajanand",
          bat1Runs: 14,
          bat1fours: 1,
          bat1sixes: 1,
          bat2Id: 20217,
          bat2Name: "Sushant Modani",
          bat2Runs: 7,
          bat2fours: 0,
          bat2sixes: 0,
          totalRuns: 21,
          totalBalls: 17,
          bat1balls: 10,
          bat2balls: 7,
          bat1Ones: 4,
          bat1Twos: 0,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 1,
          bat1Sixers: 1,
          bat2Ones: 5,
          bat2Twos: 1,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 0,
          bat2Sixers: 0,
        },
        pat_7: {
          bat1Id: 22901,
          bat1Name: "Yasir Mohammad",
          bat1Runs: 0,
          bat1fours: 0,
          bat1sixes: 0,
          bat2Id: 15475,
          bat2Name: "Nisarg Patel",
          bat2Runs: 0,
          bat2fours: 0,
          bat2sixes: 0,
          totalRuns: 1,
          totalBalls: 2,
          bat1balls: 2,
          bat2balls: 0,
          bat1Ones: 0,
          bat1Twos: 0,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 0,
          bat1Sixers: 0,
          bat2Ones: 0,
          bat2Twos: 0,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 0,
          bat2Sixers: 0,
        },
      },
    },
  ],
  matchHeader: {
    matchId: 40381,
    matchDescription: "2nd T20I",
    matchFormat: "HUN",
    matchType: "International",
    complete: true,
    domestic: false,
    matchStartTimestamp: 1640304000000,
    matchCompleteTimestamp: 1640316600000,
    dayNight: true,
    year: 2021,
    dayNumber: 1,
    state: "Complete",
    status: "Ireland won by 9 runs",
    tossResults: {},
    result: {
      resultType: "win",
      winningTeam: "Ireland",
      winningteamId: 27,
      winningMargin: 9,
      winByRuns: true,
      winByInnings: false,
    },
    revisedTarget: {},
    playersOfTheMatch: [
      {
        id: 11131,
        name: "Tucker",
        fullName: "Lorcan Tucker",
        nickName: "Tucker",
        captain: false,
        role: "Batsman",
        keeper: false,
        substitute: false,
        teamId: 0,
        battingStyle: " ",
        bowlingStyle: " ",
        teamName: " ",
        faceImageId: 191070,
      },
    ],
    playersOfTheSeries: [
      {
        id: 11131,
        name: "Tucker",
        fullName: "Lorcan Tucker",
        nickName: "Tucker",
        captain: false,
        role: "WK-Batsman",
        keeper: false,
        substitute: false,
        teamId: 27,
        battingStyle: "Right-hand bat",
        bowlingStyle: "",
        teamName: "Ireland",
        faceImageId: 191070,
      },
    ],
    matchTeamInfo: [
      {
        battingTeamId: 27,
        battingTeamShortName: "IRE",
        bowlingTeamId: 15,
        bowlingTeamShortName: "USA",
      },
      {
        battingTeamId: 15,
        battingTeamShortName: "USA",
        bowlingTeamId: 27,
        bowlingTeamShortName: "IRE",
      },
    ],
    isMatchNotCovered: false,
    team1: {
      id: 15,
      name: "United States",
      playerDetails: [],
      shortName: "USA",
    },
    team2: {
      id: 27,
      name: "Ireland",
      playerDetails: [],
      shortName: "IRE",
    },
    seriesDesc: "Ireland tour of USA, 2021",
    seriesId: 3866,
    seriesName: "Ireland tour of USA, 2021",
  },
  isMatchComplete: true,
  status: "Ireland won by 9 runs",
  videos: [],
  responseLastUpdated: 1661274274,
};

export const matchInfo = {
  matchInfo: {
    matchId: 41881,
    matchDescription: "Group A",
    matchFormat: "ODI",
    matchType: "domestic",
    complete: true,
    domestic: false,
    matchStartTimestamp: 1640410200000,
    matchCompleteTimestamp: 1640429211515,
    dayNight: false,
    year: 2021,
    state: "complete",
    team1: {
      id: 223,
      name: "Afghanistan U19",
      playerDetails: [
        {
          id: 14269,
          name: "Suliman Arabzai",
          fullName: "Suliman Arabzai",
          nickName: "Suliman Arabzai",
          captain: false,
          role: "",
          keeper: false,
          substitute: false,
          teamId: 223,
          battingStyle: "RIGHT",
          bowlingStyle: "",
          faceImageId: 182026,
        },
        {
          id: 22846,
          name: "Suliman Safi",
          fullName: "Suliman Safi",
          nickName: "Suliman Safi",
          captain: true,
          role: "",
          keeper: false,
          substitute: false,
          teamId: 223,
          battingStyle: "LEFT",
          bowlingStyle: "",
          faceImageId: 182026,
        },
        {
          id: 22856,
          name: "Allah Noor",
          fullName: "Allah Noor",
          nickName: "Allah Noor",
          captain: false,
          role: "",
          keeper: false,
          substitute: false,
          teamId: 223,
          battingStyle: "RIGHT",
          bowlingStyle: "Right Arm off break",
          faceImageId: 182026,
        },
        {
          id: 23041,
          name: "Ijaz Ahmad Ahmadzai",
          fullName: "Ijaz Ahmad Ahmadzai",
          nickName: "Ijaz Ahmad Ahmadzai",
          captain: false,
          role: "Batting Allrounder",
          keeper: false,
          substitute: false,
          teamId: 223,
          battingStyle: "RIGHT",
          bowlingStyle: "Right Arm medium",
          faceImageId: 182026,
        },
        {
          id: 14198,
          name: "Ijaz Ahmad",
          fullName: "Ijaz Ahmad Azad",
          nickName: "Ijaz Ahmad",
          captain: false,
          role: "Batsman",
          keeper: false,
          substitute: false,
          teamId: 223,
          battingStyle: "RIGHT",
          bowlingStyle: "Right Arm off break",
          faceImageId: 182026,
        },
        {
          id: 22861,
          name: "Bilal Sami",
          fullName: "Bilal Sami",
          nickName: "Bilal Sami",
          captain: false,
          role: "",
          keeper: false,
          substitute: false,
          teamId: 223,
          battingStyle: "RIGHT",
          bowlingStyle: "Right Arm medium",
          faceImageId: 182026,
        },
        {
          id: 14195,
          name: "Mohammad Ishaq",
          fullName: "Mohammad Ishaq",
          nickName: "Mohammad Ishaq",
          captain: false,
          role: "WK-Batsman",
          keeper: true,
          substitute: false,
          teamId: 223,
          battingStyle: "RIGHT",
          bowlingStyle: "",
          faceImageId: 182026,
        },
        {
          id: 22956,
          name: "Nangyalai Khan",
          fullName: "Nangyalai Khan",
          nickName: "Nangyalai Khan",
          captain: false,
          role: "",
          keeper: false,
          substitute: false,
          teamId: 223,
          battingStyle: "RIGHT",
          bowlingStyle: "",
          faceImageId: 182026,
        },
        {
          id: 15452,
          name: "Noor Ahmad",
          fullName: "Noor Ahmad",
          nickName: "Noor Ahmad",
          captain: false,
          role: "Bowler",
          keeper: false,
          substitute: false,
          teamId: 223,
          battingStyle: "RIGHT",
          bowlingStyle: "Left Arm chinaman",
          faceImageId: 226316,
        },
        {
          id: 21781,
          name: "Izharulhaq Naveed",
          fullName: "Izharulhaq Naveed",
          nickName: "Izharulhaq Naveed",
          captain: false,
          role: "Bowler",
          keeper: false,
          substitute: false,
          teamId: 223,
          battingStyle: "RIGHT",
          bowlingStyle: "Right Arm leg break",
          faceImageId: 226315,
        },
        {
          id: 23081,
          name: "Khalel Ahmad",
          fullName: "Khalel Ahmad",
          nickName: "Khalel Ahmad",
          captain: false,
          role: "Bowler",
          keeper: false,
          substitute: false,
          teamId: 223,
          battingStyle: "RIGHT",
          bowlingStyle: "Right Arm fast medium",
          faceImageId: 182026,
        },
        {
          id: 22851,
          name: "Bilal Sayedi",
          fullName: "Bilal Sayedi",
          nickName: "Bilal Sayedi",
          captain: false,
          role: "",
          keeper: false,
          substitute: true,
          teamId: 223,
          battingStyle: "RIGHT",
          bowlingStyle: "",
          faceImageId: 182026,
        },
        {
          id: 23046,
          name: "Faisal Khan Ahmadzai",
          fullName: "Faisal Khan Ahmadzai",
          nickName: "Faisal Khan Ahmadzai",
          captain: false,
          role: "Bowler",
          keeper: false,
          substitute: true,
          teamId: 223,
          battingStyle: "LEFT",
          bowlingStyle: "",
          faceImageId: 182026,
        },
        {
          id: 22866,
          name: "Bilal Ahmad",
          fullName: "Bilal Ahmad",
          nickName: "Bilal Ahmad",
          captain: false,
          role: "",
          keeper: false,
          substitute: true,
          teamId: 223,
          battingStyle: "RIGHT",
          bowlingStyle: "Right Arm fast medium",
          faceImageId: 182026,
        },
        {
          id: 22946,
          name: "Muhammadullah",
          fullName: "Muhammadullah",
          nickName: "Muhammadullah",
          captain: false,
          role: "",
          keeper: false,
          substitute: true,
          teamId: 223,
          battingStyle: "RIGHT",
          bowlingStyle: "",
          faceImageId: 182026,
        },
        {
          id: 22951,
          name: "Khyber Wali",
          fullName: "Khyber Wali",
          nickName: "Khyber Wali",
          captain: false,
          role: "",
          keeper: false,
          substitute: true,
          teamId: 223,
          battingStyle: "RIGHT",
          bowlingStyle: "",
          faceImageId: 182026,
        },
        {
          id: 22961,
          name: "Abdul Hadi",
          fullName: "Abdul Hadi",
          nickName: "Abdul Hadi",
          captain: false,
          role: "",
          keeper: false,
          substitute: true,
          teamId: 223,
          battingStyle: "RIGHT",
          bowlingStyle: "",
          faceImageId: 182026,
        },
        {
          id: 22966,
          name: "Bilal Tarin",
          fullName: "Bilal Tarin",
          nickName: "Bilal Tarin",
          captain: false,
          role: "",
          keeper: false,
          substitute: true,
          teamId: 223,
          battingStyle: "RIGHT",
          bowlingStyle: "",
          faceImageId: 182026,
        },
        {
          id: 22971,
          name: "Shahid Hassani",
          fullName: "Shahid Hassani",
          nickName: "Shahid Hassani",
          captain: false,
          role: "",
          keeper: false,
          substitute: true,
          teamId: 223,
          battingStyle: "RIGHT",
          bowlingStyle: "",
          faceImageId: 182026,
        },
      ],
      shortName: "AFGU19",
    },
    team2: {
      id: 283,
      name: "United Arab Emirates U19",
      playerDetails: [
        {
          id: 16074,
          name: "Kai Smith",
          fullName: "Kai Smith",
          nickName: "Kai Smith",
          captain: false,
          role: "Batsman",
          keeper: false,
          substitute: false,
          teamId: 283,
          battingStyle: "RIGHT",
          bowlingStyle: "",
          faceImageId: 182026,
        },
        {
          id: 22911,
          name: "Aryansh Sharma",
          fullName: "Aryansh Sharma",
          nickName: "Aryansh Sharma",
          captain: false,
          role: "",
          keeper: true,
          substitute: false,
          teamId: 283,
          battingStyle: "RIGHT",
          bowlingStyle: "",
          faceImageId: 182026,
        },
        {
          id: 12387,
          name: "Dhruv Parashar",
          fullName: "Dhruv Parashar",
          nickName: "Dhruv Parashar",
          captain: false,
          role: "",
          keeper: false,
          substitute: false,
          teamId: 283,
          battingStyle: "RIGHT",
          bowlingStyle: "",
          faceImageId: 182026,
        },
        {
          id: 14227,
          name: "Alishan Sharafu",
          fullName: "Alishan Sharafu",
          nickName: "Alishan Sharafu",
          captain: true,
          role: "Batting Allrounder",
          keeper: false,
          substitute: false,
          teamId: 283,
          battingStyle: "RIGHT",
          bowlingStyle: "Right Arm medium",
          faceImageId: 182026,
        },
        {
          id: 22831,
          name: "Punya Mehra",
          fullName: "Punya Mehra",
          nickName: "Punya Mehra",
          captain: false,
          role: "",
          keeper: false,
          substitute: false,
          teamId: 283,
          battingStyle: "RIGHT",
          bowlingStyle: "Right Arm off break",
          faceImageId: 182026,
        },
        {
          id: 16083,
          name: "Ali Naseer",
          fullName: "Ali Naseer",
          nickName: "Ali Naseer",
          captain: false,
          role: "Batsman",
          keeper: false,
          substitute: false,
          teamId: 283,
          battingStyle: "RIGHT",
          bowlingStyle: "",
          faceImageId: 182026,
        },
        {
          id: 22836,
          name: "Soorya Sathish",
          fullName: "Soorya Sathish",
          nickName: "Soorya Sathish",
          captain: false,
          role: "",
          keeper: false,
          substitute: false,
          teamId: 283,
          battingStyle: "RIGHT",
          bowlingStyle: "Right Arm medium",
          faceImageId: 182026,
        },
        {
          id: 22841,
          name: "Nilansh Keswani",
          fullName: "Nilansh Keswani",
          nickName: "Nilansh Keswani",
          captain: false,
          role: "",
          keeper: false,
          substitute: false,
          teamId: 283,
          battingStyle: "RIGHT",
          bowlingStyle: "",
          faceImageId: 182026,
        },
        {
          id: 23016,
          name: "Afzal Khan",
          fullName: "Aayan Afzal Khan",
          nickName: "Afzal Khan",
          captain: false,
          role: "",
          keeper: false,
          substitute: false,
          teamId: 283,
          battingStyle: "RIGHT",
          bowlingStyle: "Right Arm off break",
          faceImageId: 182026,
        },
        {
          id: 18683,
          name: "Adhitya Shetty",
          fullName: "Adhitya Shetty",
          nickName: "Adhitya Shetty",
          captain: false,
          role: "Bowler",
          keeper: false,
          substitute: false,
          teamId: 283,
          battingStyle: "RIGHT",
          bowlingStyle: "Right Arm leg break",
          faceImageId: 182026,
        },
        {
          id: 22906,
          name: "Sailles Jaishankar",
          fullName: "Sailles Jaishankar",
          nickName: "Sailles Jaishankar",
          captain: false,
          role: "",
          keeper: false,
          substitute: false,
          teamId: 283,
          battingStyle: "RIGHT",
          bowlingStyle: "",
          faceImageId: 182026,
        },
        {
          id: 23001,
          name: "Vijaya Raghavan",
          fullName: "Vinayak Vijaya Raghavan",
          nickName: "Vijaya Raghavan",
          captain: false,
          role: "",
          keeper: false,
          substitute: true,
          teamId: 283,
          battingStyle: "RIGHT",
          bowlingStyle: "",
          faceImageId: 182026,
        },
        {
          id: 14226,
          name: "Ronak Panoly",
          fullName: "Ronak Panoly",
          nickName: "Ronak Panoly",
          captain: false,
          role: "",
          keeper: false,
          substitute: true,
          teamId: 283,
          battingStyle: "RIGHT",
          bowlingStyle: "Right Arm medium",
          faceImageId: 182026,
        },
        {
          id: 22916,
          name: "Jash Giyanani",
          fullName: "Jash Giyanani",
          nickName: "Jash Giyanani",
          captain: false,
          role: "",
          keeper: false,
          substitute: true,
          teamId: 283,
          battingStyle: "RIGHT",
          bowlingStyle: "",
          faceImageId: 182026,
        },
        {
          id: 22921,
          name: "Shival Bawa",
          fullName: "Shival Bawa",
          nickName: "Shival Bawa",
          captain: false,
          role: "",
          keeper: false,
          substitute: true,
          teamId: 283,
          battingStyle: "RIGHT",
          bowlingStyle: "",
          faceImageId: 182026,
        },
        {
          id: 22926,
          name: "Nilansh Keswani",
          fullName: "Nilansh Keswani",
          nickName: "Nilansh Keswani",
          captain: false,
          role: "",
          keeper: false,
          substitute: true,
          teamId: 283,
          battingStyle: "RIGHT",
          bowlingStyle: "",
          faceImageId: 182026,
        },
      ],
      shortName: "UAEU19",
    },
    series: {
      id: 3926,
      name: "ACC U19 Asia Cup 2021",
      seriesType: "",
      startDate: 1640131200000,
      endDate: 1640995200000,
      seriesFolder: "2021_U19_ASIA_CUP",
      odiSeriesResult: "''",
      t20SeriesResult: "",
      testSeriesResult: "",
      tournament: true,
    },
    umpire1: {
      id: 7540,
      name: "Naresh Shah",
      country: "KEN",
    },
    umpire2: {
      id: 7244,
      name: "Sarika Prasad",
      country: "SIN",
    },
    umpire3: {
      id: 8871,
      name: "KN Anantha Padmanabhan",
      country: "IND",
    },
    referee: {
      id: 9070,
      name: "Akhtar Ahmad",
      country: "BAN",
    },
    tossResults: {
      tossWinnerId: 283,
      tossWinnerName: "United Arab Emirates U19",
      decision: "Bowling",
    },
    result: {
      resultType: "win",
      winningTeam: "Afghanistan U19",
      winningteamId: 223,
      winningMargin: 140,
      winByRuns: true,
      winByInnings: false,
    },
    venue: {
      id: 289,
      name: "ICC Academy Ground",
      city: "Dubai",
      country: "United Arab Emirates",
      timezone: "+04:00",
      latitude: "25.036563",
      longitude: "55.227611",
    },
    status: "United Arab Emirates U19 opt to bowl",
    playersOfTheMatch: [
      {
        id: 22856,
        name: "Allah Noor",
        fullName: "Allah Noor",
        nickName: "Allah Noor",
        captain: false,
        keeper: false,
        substitute: false,
        teamName: "Afghanistan U19",
        faceImageId: 182026,
      },
    ],
    playersOfTheSeries: [],
    revisedTarget: {
      reason: "",
    },
    matchTeamInfo: [
      {
        battingTeamId: 223,
        battingTeamShortName: "AFGU19",
        bowlingTeamId: 283,
        bowlingTeamShortName: "UAEU19",
      },
      {
        battingTeamId: 283,
        battingTeamShortName: "UAEU19",
        bowlingTeamId: 223,
        bowlingTeamShortName: "AFGU19",
      },
    ],
    isMatchNotCovered: false,
    HYSEnabled: 0,
  },
  venueInfo: {
    established: 2009,
    capacity: null,
    knownAs: "ICC Global Cricket Academy",
    ends: "City End, Reem Raam End",
    city: "Dubai",
    country: "United Arab Emirates",
    timezone: "+04:00",
    homeTeam: "United Arab Emirates",
    floodlights: true,
    curator: "Toby Lumsden",
    profile: null,
    imageUrl: "http://i.cricketcb.com/i/stats/fth/540x303/venue/images/289.jpg",
    ground: "ICC Academy Ground",
    groundLength: 0,
    groundWidth: 0,
    otherSports: null,
  },
};
